name: BlocksConverter
main: Frago9876543210\BlocksConverter\Main
version: 1.0
api: 
- 3.0.0 # Update
- 4.0.0
author: Frago9876543210 && SteveDev

commands:
 bs:
  description: "BlocksConverter command"
  permission: bs
permissions:
 bs:
  default: op
